import Layout from "components/Layout"
import Head from "next/head"
import { NextPageWithLayout } from "types/page"

const Home: NextPageWithLayout = () => {
  // const dispatch = useDispatch()
  return (
    <>
      <Head>
        <title>Tour 27</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-96 my-auto">
        <h1>Virtual Tours and Experiences</h1>
        <p>Hop on an virtual tour with our guides around the world!</p>
      </main>
    </>
  )
}
export default Home
Home.getLayout = (page) => {
  return <Layout>{page}</Layout>
}
