import Head from "next/head"

// eslint-disable-next-line quotes

export default function Home() {
  // const dispatch = useDispatch()
  return (
    <>
      <Head>
        <title>Tour 27</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Tour 27</main>
    </>
  )
}
